site_name: Microchip FPGA Documentation Portal
docs_dir: docs
theme:
  name: material
  logo: assets/microchip.png
  palette:
    - scheme: default
      primary: black
      accent: grey
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.sections
    - navigation.top
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
    - content.tabs.link
    - header.autohide
    - announce.dismiss
extra:
  announcement:
    type: info
    text: "Welcome to the Microchip FPGA Documentation Portal."
  footer:
    copyright: "© 2025 Microchip FPGA Documentation Portal. All rights reserved."
  extra_css:
    - assets/custom-tiles.css
plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html 
use_directory_urls: false 
