site_name: FPGA Documentation Portal
nav:
  - Home: index.md
  - Hardware: 
      - Hardware Documentation: hardware/index.html
      - Application Notes: hardware/Application Notes/index.html
      - Silicon User Guides: hardware/Silicon User Guides/index.html
      - Whitepapers: hardware/Whitepapers/index.html
  - Software:
      - Software Documentation: software/index.html
      - Release Notes: software/Release Notes/index.html
      - User Guides: software/User Guides/index.html
  - IP: 
      - IP Documentation: ip/index.html
      - IP User Guides: ip/IP User Guides/index.html
      - Reference Guides: ip/Reference Guides/index.html
docs_dir: docs
theme:
  name: material
  logo: assets/microchip.png
  palette:
    - scheme: default
      primary: black
      accent: grey
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.sections
    - navigation.top
    # - navigation.expand   # Collapsed by default now
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
    - content.tabs.link
    - header.autohide
    - announce.dismiss
extra:
  announcement:
    type: info
    text: "Welcome to the Microchip FPGA Documentation Portal."
  footer:
    copyright: "© 2025 Microchip FPGA Documentation Portal. All rights reserved."
  extra_css:
    - assets/custom-tiles.css
plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html 
use_directory_urls: false 
