site_name: FPGA Documentation Portal
nav:
  - Home: index.md
  - Hardware: 
      - Hardware Documentation: Hardware/index.md
      - Application Notes: Hardware/Application Notes/index.md
      - Silicon User Guides: Hardware/Silicon User Guides/index.md
      - Whitepapers: Hardware/Whitepapers/index.md
  - Software:
      - Software Documentation: Software/index.md
      - Release Notes: Software/Release Notes/index.md
      - User Guides: Software/User Guides/index.md
  - IP: IP/index.md
      - IP Documentation:
      - IP User Guides: IP/IP User Guides/index.md
      - Reference Guides: IP/Reference Guides/index.md
docs_dir: docs
theme:
  name: material
  logo: assets/microchip.png
  palette:
    - scheme: default
      primary: black
      accent: grey
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.sections
    - navigation.top
    # - navigation.expand   # Collapsed by default now
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
    - content.tabs.link
    - header.autohide
    - announce.dismiss
extra:
  announcement:
    type: info
    text: "Welcome to the Microchip FPGA Documentation Portal."
  footer:
    copyright: "© 2025 Microchip FPGA Documentation Portal. All rights reserved."
  extra_css:
    - assets/custom-tiles.css
plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html 
use_directory_urls: false 
