site_name: FPGA Documentation Portal
nav:
  - Home: index.md
  - Hardware:
      - Hardware Documentation: Hardware/index.html
      - Application Notes: Hardware/ApplicationNotes/index.html
      - Silicon User Guides: Hardware/SiliconUserGuides/index.html
      - Whitepapers: Hardware/Whitepapers/index.html
  - Software:
      - Software Documentation: Software/index.html
      - Release Notes: Software/ReleaseNotes/index.html
      - User Guides: Software/UserGuides/index.html
  - IP:
      - IP Documentation: IP/index.md
      - IP User Guides: IP/IPUserGuides/index.html
      - Reference Guides: IP/ReferenceGuides/index.html
docs_dir: docs
theme:
  name: material
  logo: assets/microchip.png
  favicon: assets/microchip.png
  palette:
    - scheme: default
      primary: black
      accent: grey
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - navigation.sections
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.tabs
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - toc.follow

extra:
  announcement:
    type: info
    text: "Welcome to the Microchip FPGA Documentation Portal."
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/<your-username>/<your-repo>
  generator: false
  extra_css:
    - assets/custom-tiles.css
    - assets/toc-right.css

plugins:
  - search:
      lang: en
      separator: '[\s\-_]+'
  - awesome-pages:
      filename: .pages
      collapse_single_pages: true
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3

use_directory_urls: true

extra_javascript:
  - assets/toc-right.js
